spring.application.name=server

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI}

# Server
server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG

# Local storage
storage.upload-dir=uploads

# Cloudinary
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}



# spring.application.name=server

# # MongoDB Atlas
# spring.data.mongodb.uri=mongodb+srv://vipinbagri43_db_user:Vipin12345@campusmarketplace.466yqxm.mongodb.net/campus_marketplace?retryWrites=true&w=majority&appName=CampusMarketPlace
# # Server
# server.port=8080

# # JWT
# jwt.secret=CampusMarketPlaceSecretKeyForJwtAuthentication2026VeryStrongKey
# jwt.expiration=86400000

# # Logging
# logging.level.org.springframework.security=DEBUG

# storage.upload-dir=uploads

# cloudinary.cloud-name=${wnvp6jup}
# cloudinary.api-key=${663259154474688}
# cloudinary.api-secret=${s2cptoqN5jT6s15ilO7KyqKGycE}