spring.application.name=server

# MongoDB Atlas
spring.data.mongodb.uri=mongodb+srv://vipinbagri43_db_user:Vipin12345@campusmarketplace.466yqxm.mongodb.net/campus_marketplace?retryWrites=true&w=majority&appName=CampusMarketPlace
# Server
server.port=8080

# JWT
jwt.secret=CampusMarketPlaceSecretKeyForJwtAuthentication2026VeryStrongKey
jwt.expiration=86400000

# Logging
logging.level.org.springframework.security=DEBUG